/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EquipmentManufacturerEnterprise;
import Business.Network.Network;
import Business.Organization.CustomerServiceOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.PatientDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FeedbackWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dongyueli
 */
public class FeedbackToEuipmentManufactureJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private PatientOrganization patientOrganization;

    //private PatientDirectory patientDirectory;
    /**
     * Creates new form FeedbackToEuipmentManufactureJPanel
     */
    public FeedbackToEuipmentManufactureJPanel(JPanel userProcessContainer, UserAccount userAccount, PatientOrganization patientOrganization, Enterprise enterprise, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        this.patientOrganization = (PatientOrganization) patientOrganization;
        this.enterprise = enterprise;
        //this.patientDirectory = patientDirectory;
        populateViewFeedbackFromEquipmentManufactureJTable();
    }

    public void populateViewFeedbackFromEquipmentManufactureJTable() {
        DefaultTableModel model = (DefaultTableModel) viewFeedbackFromEquipmentManufactureJTable.getModel();

        model.setRowCount(0);
        if (userAccount.getWorkQueue().getWorkRequestList() != null) {
            for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
                if (request != null) {
                    FeedbackWorkRequest feedbackWorkRequest = (FeedbackWorkRequest) request;
                    Object[] row = new Object[2];
                    feedbackWorkRequest.setDate();
                    row[0] = feedbackWorkRequest.getDate();
                    row[1] = feedbackWorkRequest.getStatus();
                    model.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        sentJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackJTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton12 = new javax.swing.JRadioButton();
        backJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewFeedbackFromEquipmentManufactureJTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Feedback");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 17, 124, -1));

        sentJButton.setText("Send Feedback");
        sentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentJButtonActionPerformed(evt);
            }
        });
        add(sentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 497, -1, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 472, -1, -1));

        jLabel3.setText("We welcome problem reports, feature ideas and general comments.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 384, -1, -1));

        feedbackJTextArea.setColumns(20);
        feedbackJTextArea.setRows(5);
        jScrollPane1.setViewportView(feedbackJTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 418, 422, 67));

        jLabel4.setText("1. What do you think of the design of our products?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 99, -1, -1));

        jLabel5.setText("Please evaluate our products by selecting one of the options for each question.   ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 65, -1, -1));

        jLabel6.setText("2.What do you think of the weight of our products?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 177, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Not satisfied");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 133, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Satisfied");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 133, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Very satisfied");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 133, -1, -1));

        jLabel7.setText("We will feedback to you as soon as possible and your satisfaction is guaranteed.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 532, -1, -1));

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Not satisfied");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 205, -1, -1));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Satisfied");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 205, -1, -1));

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Very satisfied");
        add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 205, -1, -1));

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setText("Not satisfied");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 274, -1, -1));

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setText("Satisfied");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 274, -1, -1));

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText("Very satisfied");
        add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 274, -1, -1));

        jLabel8.setText("3.What do you think of the power of our products?");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 246, -1, -1));

        buttonGroup4.add(jRadioButton10);
        jRadioButton10.setText("Satisfied");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 343, -1, -1));

        buttonGroup4.add(jRadioButton11);
        jRadioButton11.setText("Very satisfied");
        add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 343, -1, -1));

        jLabel10.setText("4.What do you think of the performance of our products?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 315, -1, -1));

        buttonGroup4.add(jRadioButton12);
        jRadioButton12.setText("Not satisfied");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 343, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 698, -1, -1));

        viewFeedbackFromEquipmentManufactureJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Timestamp", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(viewFeedbackFromEquipmentManufactureJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 566, 510, 114));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void sentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentJButtonActionPerformed
        // TODO add your handling code here:


        FeedbackWorkRequest request = new FeedbackWorkRequest();
        request.setFeedbackMessage(feedbackJTextArea.getText());
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setDate();
        
//        jRadioButton1.addItemListener(this);
        

        if (jRadioButton1.isSelected()) {
            request.setNotsatisfied1(jRadioButton1.getText());
        } else if (jRadioButton2.isSelected()) {
            request.setSatisfied1(jRadioButton2.getText());
        } else if (jRadioButton3.isSelected()) {
            request.setVerysatisfied1(jRadioButton3.getText());
        }

        if (jRadioButton4.isSelected()) {
            request.setNotsatisfied2(jRadioButton4.getText());
        } else if (jRadioButton5.isSelected()) {
            request.setSatisfied2(jRadioButton5.getText());
        } else if (jRadioButton6.isSelected()) {
            request.setVerysatisfied2(jRadioButton6.getText());
        }

        if (jRadioButton7.isSelected()) {
            request.setNotsatisfied3(jRadioButton7.getText());
        } else if (jRadioButton8.isSelected()) {
            request.setSatisfied3(jRadioButton8.getText());
        } else if (jRadioButton9.isSelected()) {
            request.setVerysatisfied3(jRadioButton9.getText());
        }

        if (jRadioButton12.isSelected()) {
            request.setNotsatisfied4(jRadioButton12.getText());
        } else if (jRadioButton10.isSelected()) {
            request.setSatisfied4(jRadioButton10.getText());
        } else if (jRadioButton11.isSelected()) {
            request.setVerysatisfied4(jRadioButton11.getText());
        }
        
        Network targetNetwork = null;

        for (Network network : ecoSystem.getNetworkList()) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e == enterprise) {
                    targetNetwork = network;
                    break;
                }
            }
        }
        
        Organization org = null;
        for (Enterprise e : targetNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof EquipmentManufacturerEnterprise) {
                EquipmentManufacturerEnterprise emfe =(EquipmentManufacturerEnterprise)e;
                for(Organization o:emfe.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof CustomerServiceOrganization){
                        org=o;
                        break;
                    }
                }
            }
        }
       
        
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Success! We will feedback to you as soon as possible and your satisfaction is guaranteed.");
        }
        populateViewFeedbackFromEquipmentManufactureJTable();
    }//GEN-LAST:event_sentJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextArea feedbackJTextArea;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton sentJButton;
    private javax.swing.JTable viewFeedbackFromEquipmentManufactureJTable;
    // End of variables declaration//GEN-END:variables
}
